name: Forex Alert Runner

on:
  # schedule:
  #   - cron: '0 * * * *'  # Every hour UTC
  workflow_dispatch:

jobs:
  run-forex-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run forex alert
        env:
          sender_gmail: ${{ secrets.sender_gmail }}
          sender_app_password: ${{ secrets.sender_app_password }}
          receiver_gmail: ${{ secrets.receiver_gmail }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python forexAlert.py
